Proposed changes to CLI to support manual testing
conjurdemos/dap-intro pull request #71
Opened 2020-08-25 16:17 UTC by jvanderhoof

This is a proposed interface change to allow this project to support common customer workflows. The goal of this interface is to simplify manual testing of a wide variety of customer scenarios to ensure product integrity.

2020-09-14 15:04 UTC, h-artzi requested changes

2020-09-14 15:04 UTC, h-artzi commented on README.md
> +$ bin/api --load-policy-and-values
```
 bin/api --load-policy-and-values
{"created_roles":{},"version":3}curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to conjur-master.mycompany.local:443
➜  dap-intro git:(cli-workflows) bin/api --fetch-secrets
--fetch-secrets is not a valid option
```

2020-09-14 15:10 UTC, jvanderhoof commented on bin/dap
> +    # --disable-auto-failover ) CMD='_disable_autofailover' ; shift ;;
I'm going to remove this.  Disabling auto-failover is fraught with peril and doesn't result in auto-failover functionality being fully removed. The script un-enrolls ETCD nodes, which gets us to the point where we can upgrade.

2020-09-14 15:34 UTC, jvanderhoof commented on README.md
> +    --disable-auto-failover     Removes nodes into and auto-failover cluster
great catch!

2020-09-14 15:41 UTC, jvanderhoof commented on system/configuration/certificates/ca-chain.cert.pem
> +-----BEGIN CERTIFICATE-----
I've filed issue #73 to capture this work.

2020-09-14 15:42 UTC, jvanderhoof commented on README.md
>      --dry-run                   Displays the commands that will be run, without actually running them
Good catch. I'm going to pull all that out of the README.

2020-09-14 21:00 UTC, jvanderhoof commented on README.md
> +$ bin/api --load-policy-and-values
Added 😄 .  I also updated the Readme

2020-09-14 21:25 UTC, h-artzi commented
fetch secrets is good, but a simple add on might be a set secrets as well. To ensure they don't return empty strings.

2020-09-15 13:23 UTC, jvanderhoof commented
@h-artzi, this tool is intended to simplify common workflows (for engineers).  I don't want to replace the Conjur CLI.  Is there anything else this needs, or can we merge these improvements?

2020-09-15 13:23 UTC, h-artzi commented on README.md
> +|--password `<password>`|configuration|Uses a non-default password for authentication|• Authenticates<br>• Sets variable values|Requires `--load-policy` before running|
Authenticates<br>• Sets variable is in the wrong row. Need to be moved down one

2020-09-15 13:31 UTC, jvanderhoof commented on README.md
> +|--password `<password>`|configuration|Uses a non-default password for authentication|• Authenticates<br>• Sets variable values|Requires `--load-policy` before running|
fixed

2020-09-15 13:34 UTC, h-artzi approved these changes

2020-09-15 14:28 UTC, merged