Certificates are generated prior to import
conjurdemos/dap-intro pull request #75
Opened 2020-09-23 20:16 UTC by jvanderhoof

This PR uses CFSSL to generate a root, intermediate, and leaf certificates for a DAP cluster.  CFSSL provides a much cleaner interface for certificate generation than OpenSSL (IMO). This change means certificates are generated on request and no longer will expire.

2020-09-25 14:14 UTC, sgnn7 requested changes
@jvanderhoof Looks good - left some comments. I think it also may be good for a more-robust test  that we do 2 intermediate certs in the chain to really make it close to what we might expect at user deployments.

2020-09-25 14:14 UTC, sgnn7 commented on bin/dap
> +  bin/generate-certs
I know it's unrelated directly but I think `./bin/dap` needs a default action. Running it without any parameters literally gives no output/feedback whatsoever:
```sh-session
$  ./bin/dap 
$
```

2020-10-01 16:09 UTC, jvanderhoof commented on artifacts/certificate-generator/generate-certs-script
> +#!/bin/ash -e
I'll add the failure for pipes in.  Ash is used because this whole thing is run inside an Alpine container.

2020-10-01 16:10 UTC, jvanderhoof commented on artifacts/certificate-generator/Dockerfile
> +    cd cfssl && make
I'll take a look.  Installing a binary is WAY faster than building from source 😛 .

2020-10-01 16:12 UTC, jvanderhoof commented on bin/dap
> +  bin/generate-certs
Good call.  A no-op without visibility isn't a great experience.

2020-11-30 23:49 UTC, jvanderhoof commented on artifacts/certificate-generator/Dockerfile
> +    cd cfssl && make
The binaries are super out-of-date 😞 . I'm going to keep the build here for now.

2020-12-14 23:29 UTC, merged