Adds End-to-End testing for a DAP release
conjurdemos/dap-intro pull request #85
Opened 2020-12-15 17:33 UTC by jvanderhoof

#### What does this PR do? Is there any background context you want to provide?
This PR adds a series of end-to-end tests for the DAP appliance.

#### What ticket does this PR close?
Connects to [aam-architecture#8](https://github.com/conjurinc/aam-architecture/issues/8)

#### Where should the reviewer start? How should this functionality be validated?
Top-down, I'd recommend reviewing:
- Feature - `features/cluster.feature`
- Steps - `features/step_definitions/dap_configuration.rb`, `features/step_definitions/dap_validation.rb`
- Provider - `ci/providers/docker_compose.rb`

#### Reviewers
- @jtuttle, @micahlee - I'd love feedback on the approach and areas of improvement
- @alexkalish - I'd love feedback on the scope of the tests

2020-12-16 14:26 UTC, micahlee requested changes
Looking good!

I just a few suggestions for changes before merging. Thanks!

2020-12-16 14:26 UTC, micahlee commented on ci/bin/end-to-end-tests
> +    docker pull registry2.itci.conjur.net/conjur-appliance:$version
I believe the current infra guidance is to use `registry.tld` rather than `registry2.itci.conjur.net`.

2020-12-16 14:26 UTC, micahlee commented on ci/bin/end-to-end-tests
> +#!/bin/bash -e
This script is long enough now (with helper functions), that it probably warrants a `main` function implemented at the top to become the entrypoint to reading this.

2020-12-16 14:26 UTC, micahlee commented on ci/bin/end-to-end-tests
> +prepare() {
This should probably have a more descriptive name (prepare what?).

2020-12-16 14:26 UTC, micahlee commented on ci/bin/end-to-end-tests
> +providers=('docker')
This should be defined at the top of the file to make it clear that this is a configuration that should be set.

2020-12-16 14:26 UTC, micahlee commented on ci/providers/interface.rb
> +    class Interface
So... I'm channeling my @jonahx when I say this, but this strikes me as odd and unexpected for Ruby code.

It's clear to me though, and I don't have a better suggestion. So I'm just tagging him at this point to perhaps advise on ideas for achieving the end result of documenting the interface without pretending there are interfaces in Ruby.

2020-12-16 14:26 UTC, micahlee commented on ci/providers/interface.rb
> +    class Interface
Will this always show up in error messages as `CI::Providers::Interface`? If not, it should probably have a more descript name (e.g. `ProviderInterface`).

2020-12-16 14:26 UTC, micahlee commented on features/step_definitions/world.rb
> +  @current_version = '5.12.4'
A note for future improvement:

It would be nice to see a lot of this data for versions, current versions, and configured providers to move to a config file, rather than live in the source and scripts.

2020-12-16 14:26 UTC, micahlee commented on ci/bin/end-to-end-tests
> +#!/bin/bash -e
Has this script been linted with shellcheck? There are a few issues in here I would expect it to report on (e.g. argument quoting).

2020-12-16 14:26 UTC, micahlee commented on features/cluster.feature
> +  Given a DAP master is deployed
These should use active rather than passive voice. For example:
```
Given I deploy a DAP Master
And I deploy one Follower
...
```

2020-12-16 14:26 UTC, micahlee commented on bin/dap
> +    fi
The indenting looks off here. It could be worth running shellcheck on this script if you haven't already.

2020-12-16 14:26 UTC, micahlee commented on bin/dap
> +prepare_configuration() {
Should this just be named `prepare_docker_network` or even `create_docker_network`?

2020-12-16 14:26 UTC, micahlee commented on ci/providers/docker_compose.rb
> +      def wait_for_failover_to_complete(sleep_for: 10)
This could just be `wait_for_healthy_master`, right?

2020-12-16 14:26 UTC, micahlee commented on ci/providers/docker_compose.rb
> +              # Not sure if this is a bug, but following an auto-failover, we
We have a bug issue for this here: https://github.com/conjurinc/evoke/issues/544

2020-12-16 15:26 UTC, jvanderhoof commented on ci/providers/interface.rb
> +    class Interface
I had a similar thought when writing it. I'm looking for a simple mechanism to simplify new provider development.  I'll play around some more to see if another pattern makes more sense.

2020-12-16 21:39 UTC, jvanderhoof commented on bin/dap
> +    fi
Good catch! Shellcheck didn't flag that locally 😞 .

2020-12-16 23:48 UTC, jvanderhoof commented on ci/bin/end-to-end-tests
> +    docker pull registry2.itci.conjur.net/conjur-appliance:$version
Using `registry.tld` failed locally for me. I'd like to make sure everyone can run these tests locally, if possible.

2020-12-16 23:48 UTC, jvanderhoof commented on ci/bin/end-to-end-tests
> +#!/bin/bash -e
done!

2020-12-17 15:32 UTC, micahlee approved these changes
LGTM, thanks for the clean-ups!

2020-12-17 16:11 UTC, merged