Add DAP Intro Option for Node Certification Rotation
conjurdemos/dap-intro pull request #88
Opened 2021-02-09 19:12 UTC by micahlee

This PR modifies DAP intro in a couple of ways:

* It updates the HAProxy config to support older versions of DAP by using the standard HTTPS port (443) for health checks, rather than rely on the newer HTTP health check on port 444.

* It adds a procedure flag to dap intro to rotate the node certificates called `--rotate-custom-certificates`. This allows for quickly testing certificate rotation for the Master, Standbys, and Follower in DAP Intro.

2021-02-10 19:32 UTC, h-artzi requested changes

2021-02-10 19:32 UTC, h-artzi commented on artifacts/certificate-generator/generate-certs-script
> +    cat $certificate_path/root_ca/ca.pem \
This backwards from the convention. It should be intermediate, then root.

2021-02-10 19:32 UTC, h-artzi commented on bin/dap
> +  #_rebase_standby_replication
Is this commented out on purpose?

2021-02-10 21:19 UTC, micahlee commented on artifacts/certificate-generator/generate-certs-script
> +    cat $certificate_path/root_ca/ca.pem \
Interesting. That's not a new change, I just moved where it happens

I'll change it though and make sure everything still works as expected. Thanks!

2021-02-10 21:19 UTC, micahlee commented on bin/dap
> +  #_rebase_standby_replication
Nope, I need to remove that. Thanks!

2021-02-10 21:22 UTC, h-artzi commented on artifacts/certificate-generator/generate-certs-script
> +    cat $certificate_path/root_ca/ca.pem \
I currently have a PR open on dap-intro that addresses this "issue", but I'll close it once this is merged!

2021-02-10 21:33 UTC, micahlee commented
Alright, @h-artzi, this should be ready for another look. Thanks!

2021-02-11 14:39 UTC, h-artzi approved these changes
LGTM!

2021-02-11 14:45 UTC, merged